CREATE DATABASE VENDOR;

CREATE SEQUENCE seq_seller
	INCREMENT 1;
	
CREATE TABLE IF NOT EXISTS seller (
	id SERIAL PRIMARY KEY,
	lastname VARCHAR(255) NOT NULL,
	status INTEGER NOT NULL,
	city VARCHAR(255)
);


ALTER TABLE seller ALTER COLUMN ID
SET DEFAULT next_val('seq_seller');

INSERT INTO SELLER (lastname, status, city)
VALUES ('ПЕТРОВ', 15, 'МОСКВА'), ('СИДОРОВ', 10, 'МОСКВА'), ('СИДОРОВ', 10, 'МОСКВА'), ('ВОЛКОВ', 20, 'КИЕВ');



SELECT * FROM SELLER;


CREATE TABLE IF NOT EXISTS DETAIL (
	ID SERIAL PRIMARY KEY,
	detail_name VARCHAR(255),
	color VARCHAR(255),
	weight INTEGER,
	city VARCHAR(255)
); 




CREATE TABLE SellerDetail ( 
	ID SERIAL PRIMARY KEY NOT NULL,
	SELLER_ID INT NOT NULL,
	DETAIL_ID INT NOT NULL,
	QUANTITY INT NOT NULL DEFAULT 0,
	CONSTRAINT sellerdetail_seller_id_fk FOREIGN KEY (seller_id) REFERENCES SELLER(ID) ON DELETE CASCADE ON UPDATE NO ACTION,
);

!CASCADE 
!NO ACTION 
!RESTRICT
!SET DEFAULT == SET NULL


ALTER TABLE sellerdetail ADD CONSTRAINT
	sellerdetail_check CHECK (QUANTITY >= 0);

ALTER TABLE sellerdetail ADD CONSTRAINT
	sellerdetail_detail_id_fk FOREIGN KEY (detail_id) REFERENCES DETAIL(ID) ON DELETE CASCADE ON UPDATE NO ACTION;

INSERT INTO DETAIL (DETAIL_NAME, COLOR, WEIGHT, CITY) 
VALUES ('ГАЙКА','КРАСНЫЙ',12,'ВОРОНЕЖ'), ('БОЛТ','ЗЕЛЕНЫЙ',17,'МОСКВА'), ('ШАЙБА','ГОЛУБОЙ',17,'МИНСК'),
       ('ШАЙБА','КРАСНЫЙ',14,'ВОРОНЕЖ'), ('ШУРУП','ГОЛУБОЙ',12,'МОСКВА'), ('ГВОЗДЬ','КРАСНЫЙ',19,'ВОРОНЕЖ');

SELECT * FROM SELLER

UPDATE SELLER SET LASTNAME='ВОЛКОВ', STATUS = 20, CITY = 'КИЕВ' WHERE ID = 5

ИВАНОВ	20	ВОРОНЕЖ
ПЕТРОВ	15	МОСКВА
СИДОРОВ	10	МОСКВА
ЗАЙЦЕВ	30	ВОРОНЕЖ
ВОЛКОВ	20	КИЕВ



SELECT DISTINCT LASTNAME FROM SELLER AS S INNER JOIN SELLERDETAIL AS SD ON S.ID = SD.ID
WHERE SD.ID = (SELECT ID FROM DETAIL WHERE DETAIL_NAME = 'БОЛТ');


SELECT LASTNAME FROM SELLER S
WHERE EXISTS (SELECT 1 FROM DETAIL SUB_D JOIN SELLERDETAIL SUB_SD)

INSERT INTO SELLERDETAIL (SELLER_ID, DETAIL_ID, QUANTITY)
VALUES (1, 1, 300), (1,2,200), (1,3,400), (1,4,200), (1,5,100), (1,6,100), (2, 1, 300), (2,2,400), (3,3,200), (4,2,200), (4,4,300), (4,5,400);

SELECT * FROM SELLERDETAIL

SELECT LASTNAME FROM SELLER S
WHERE NOT EXISTS (SELECT 1 FROM DETAIL SUB_D WHERE NOT EXISTS (SELECT 1 FROM SELLERDETAIL SUB_SD WHERE  S.ID = SUB_SD.ID AND SUB_D.ID = SUB_D.ID));


SELECT COUNT(DISTINCT DETAIL.ID) FROM SELLERDETAIL SD GROUP BY SD.SELLER_ID HAVING COUNT(DISTINCT DETAIL.ID) = (SELECT COUNT(*) FROM DETAIL)


SELECT LASTNAME FROM SELLER S
WHERE NOT EXISTS (SELECT 1 FROM DETAIL SUB_D WHERE EXISTS (SELECT 1 FROM SELLERDETAIL SUB_SD WHERE  S.ID = SUB_SD.SELLER_ID AND SUB_D.ID = SUB_D.ID AND SUB_D.DETAIL_NAME = 'ШАЙБА'));

SELECT LASTNAME FROM SELLER S
WHERE NOT EXISTS (SELECT 1 FROM DETAIL SUB_D WHERE NOT EXISTS (SELECT 1 FROM SELLERDETAIL SUB_SD WHERE  S.ID = SUB_SD.SELLER_ID AND SUB_D.ID = SUB_D.ID));










